apiVersion: v1
kind: Service
metadata:
  name: af-location-svc
  labels:
    app: assignforce
spec:
  ports:
    - port: 10001
      targetPort: loc-http
      protocol: TCP
  selector:
    service: location