spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:local-service-db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 'password'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      show-sql: true
      use_sql_comments: true